### ISSUE TITLE
Feature Request: Lyrics Tag, Extensible print

### ISSUE THREAD

**Issue by alivefromupstairs** [kAworu/tagutil#29]
**motivation:**
I wish to use `tagutil` to preview music tags in my file manager. It would be great if we could format the output of `print` as such: 
```fish
$ tagutil print 'track artist lyrics' 01-i-want-wind-to-blow.mp3
#no header for a single file
track: 01
artist: The Microphones
lyrics: The thunder clouds broke up
           The rain dried up
           The lightning let up
           The clacking shutters just shut up
```
also, IMO, I think print should not have "unnecessary" characters (e.g., `-` proceeding tags and `---`) and only have relevant information to make it easy to be used in other contexts (preferably with calling `grep`/`awk`).

**Comment by kAworu** [comment]
Hello @alivefromupstairs,

Thank you for your issue and clear explanation. Let me elaborate about the rational behind the current `tagutil` print format.

*Vorbis Comments* are very flexible. First, you can have more than one value for a given key (e.g. several `artist` tags), and second, the tags order is free. Tools like`grep`, `sed`, and (to a lesser extend) `awk`, are the most effective when dealing with well-defined, line-by-line inputs (e.g. `/etc/passwd`, log files, etc.).

Consequently, `tagutil` default output format is [YAML][] which allow to concisely express ordered key / value pairs. As it aim to strike a balance between "human friendly" and "serializable", there is some friction (i.e the "unecessary" characters).

To answer your request, a custom output format is very easy to achieve. You can either wrap or pipe into a custom script parsing tagutil's [YAML][] or [JSON][] output. For example this Ruby script does about what you want when called as `tagutil 01-i-want-wind-to-blow.mp3 | ruby format.rb`:

```ruby
require 'yaml'
(YAML.load STDIN.read).each do |kv|
  key, val = kv.first
  puts "#{key}: #{val.to_s.split(/\n/).join("\n\t")}"
end

```

[YAML]: https://en.wikipedia.org/wiki/YAML
[JSON]: https://en.wikipedia.org/wiki/JSON
